# Generated by Django 5.1.2 on 2024-10-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(max_length=2083, verbose_name='Product Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Price')),
                ('available', models.BooleanField(default=True, verbose_name='Product Availability')),
                ('image', models.ImageField(blank=True, null=True, upload_to='logs', verbose_name='Product Image')),
            ],
        ),
    ]
